name: flutter_facebook_image_picker
description: Flutter plugin that allows you to display Facebook multi image picker on iOS and Android.
version: 0.0.11
author: Radoslav Vitanov <radoslav.vitanov@icloud.com>
homepage: https://github.com/Sh1d0w/flutter_facebook_image_picker

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.3+16
  throttle_debounce: ^0.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

environment:
    sdk: ">=2.0.0-dev.28.0 <3.0.0"
    flutter: ">=0.1.4 <2.0.0"